### ISSUE TITLE
Daily Consumption

### ISSUE THREAD

**Issue by tobenski** [klatremis/esphome-for-deye#24]
Hi There, 

I was trying to create a Daily consumption sensor, and i believe the modbus adress is 526 but it seams the messurment is of by quite a bit. (a least compared to the Solarman Logger interface)

My sensor code is this: 
```
 - platform: modbus_controller #Daily Consumption
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 10
    name: ${device_type}-Daily Consumption
    id: ${device_type}_Daily_consumption
    register_type: holding
    address: 526
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 2
    value_type: U_WORD
    filters:
      - multiply: 0.1
```
 
Have you tried getting this sensor to work?
