### ISSUE TITLE
Modbus-register

### ISSUE THREAD

**Issue by dowermyr** [klatremis/esphome-for-deye#8]
Hi! Do you have the modbus-register for this? I wantto add som points

**Comment by dowermyr** [comment]
Trying to find something that would trigger discharge of battery to sell to grid. Any idea?

**Comment by kababoom** [comment]
I use this for the ESP:
```

select:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "sun3p-Limit control mode"
    id: sun3p_limit_control_mode
    address: 142
    value_type: U_WORD
    optionsmap:
      "Allow Export": 0
      # "Essentials": 1
      "Zero Export": 2


```
Then something like this for the card:
```

type: entities
entities:
  - entity: select.sun3p_limit_control_mode
    name: Limit Mode
  - entity: number.sun3p_maximum_battery_discharge_current
  - entity: number.sun3p_maximum_battery_charge_current

```

<img width="471" alt="image" src="https://user-images.githubusercontent.com/16404944/231244733-f6b3718e-b364-44ca-bf0b-94038d8f4e43.png">
